import { StyleSheet } from 'react-native';
import type { ColorsType } from '@/styles/colors';

export const createStyles = (colors: ColorsType) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.surfaceCardLow,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        height: 70,
        backgroundColor: colors.surfaceCard,
    },
    menuButton: {
        width: 40,
        height: 40,
        justifyContent: 'center',
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: '800',
        color: colors.textPrimary,
    },
    avatarMini: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.surfaceLight,
        borderWidth: 1.5,
        borderColor: colors.iconColor,
        justifyContent: 'center',
        alignItems: 'center',
    },
    scrollContent: {
        paddingBottom: 40,
    },
    introSection: {
        paddingHorizontal: 25,
        paddingTop: 30,
        paddingBottom: 20,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '800',
        color: colors.textPrimary,
        marginBottom: 8,
    },
    sectionSubtitle: {
        fontSize: 15,
        color: colors.textMuted,
        lineHeight: 22,
        marginBottom: 15,
    },
    markAllButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surfaceLight,
        alignSelf: 'flex-start',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 12,
    },
    markAllText: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.iconColor,
        marginLeft: 8,
    },
    filterContainer: {
        paddingHorizontal: 20,
        paddingVertical: 20,
        gap: 10,
    },
    filterTab: {
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 25,
        backgroundColor: colors.surfaceLight,
        marginRight: 8,
    },
    filterTabActive: {
        backgroundColor: colors.primary,
    },
    filterTabText: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.textMuted,
    },
    filterTabTextActive: {
        color: '#FFFFFF',
    },
    listContainer: {
        paddingHorizontal: 20,
    },
    banner: {
        borderRadius: 24,
        padding: 24,
        marginBottom: 16,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
    },
    bannerTitle: {
        fontSize: 24,
        fontWeight: '800',
        color: '#FFFFFF',
        marginBottom: 10,
    },
    bannerText: {
        fontSize: 15,
        color: '#FFFFFF',
        lineHeight: 22,
        opacity: 0.9,
    },
    bannerLink: {
        marginTop: 20,
        alignSelf: 'flex-start',
    },
    bannerLinkText: {
        color: '#FFFFFF',
        fontWeight: '800',
        fontSize: 15,
    },
    loadMore: {
        flexDirection: 'column',
        alignItems: 'center',
        marginTop: 20,
        gap: 8,
    },
    loadMoreText: {
        fontSize: 15,
        fontWeight: '700',
        color: colors.iconColor,
    },
    itemContainer: {
        backgroundColor: colors.surfaceCard,
        borderRadius: 24,
        padding: 20,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
    },
    itemHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    iconBg: {
        width: 48,
        height: 48,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    criticalIcon: {
        backgroundColor: colors.errorLight,
    },
    logIcon: {
        backgroundColor: colors.surfaceLight,
    },
    textMainContainer: {
        flex: 1,
        marginLeft: 16,
    },
    rowBetween: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 4,
    },
    itemTitle: {
        fontSize: 16,
        fontWeight: '800',
        color: colors.textPrimary,
        flex: 0.8,
        lineHeight: 20,
    },
    itemTime: {
        fontSize: 11,
        fontWeight: '600',
        color: colors.iconMuted,
        textTransform: 'uppercase',
    },
    itemDescription: {
        fontSize: 14,
        color: colors.textMuted,
        lineHeight: 20,
    },
    unreadIndicator: {
        width: 4,
        height: 12,
        backgroundColor: colors.dotRed,
        borderRadius: 2,
        marginLeft: 8,
        marginTop: 4,
    },
    buttonRow: {
        flexDirection: 'row',
        marginTop: 20,
        gap: 12,
        alignItems: 'center',
    },
    primaryBtn: {
        backgroundColor: colors.primary,
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 10,
    },
    primaryBtnText: {
        color: colors.textInverse,
        fontSize: 14,
        fontWeight: '700',
    },
    secondaryBtn: {
        paddingVertical: 10,
        paddingHorizontal: 12,
    },
    secondaryBtnText: {
        color: colors.iconColor,
        fontSize: 14,
        fontWeight: '700',
    },
});
